-- 1. daily_verses tablosu
CREATE TABLE IF NOT EXISTS public.daily_verses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_year INT NOT NULL UNIQUE CHECK (day_of_year >= 1 AND day_of_year <= 366),
    surah_no INT NOT NULL,
    ayah_no INT NOT NULL,
    arabic TEXT NOT NULL,
    meal_tr TEXT NOT NULL,
    source_name TEXT NOT NULL,
    short_text TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. daily_hadiths tablosu
CREATE TABLE IF NOT EXISTS public.daily_hadiths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_year INT NOT NULL UNIQUE CHECK (day_of_year >= 1 AND day_of_year <= 366),
    arabic TEXT,
    text_tr TEXT NOT NULL,
    narrator TEXT NOT NULL,
    source_book TEXT NOT NULL,
    source_no TEXT,
    short_text TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. RLS Açma
ALTER TABLE public.daily_verses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_hadiths ENABLE ROW LEVEL SECURITY;

-- 4. Salt Okunur (SELECT) Politikaları: anon ve authenticated erişebilir
CREATE POLICY "Anonim kullanıcılar günlük ayetleri okuyabilir"
ON public.daily_verses
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Anonim kullanıcılar günlük hadisleri okuyabilir"
ON public.daily_hadiths
FOR SELECT
TO anon, authenticated
USING (true);
